Repository TUM-Dev/gocast_mobile, pull requests merged in 2023-12, with the labels that each got.

#108 107 fix error reload
  lib/base/networking/api/gocast/api_v2.pb.dart
  lib/base/networking/api/gocast/api_v2.pbenum.dart
  lib/base/networking/api/gocast/api_v2.pbgrpc.dart
  lib/base/networking/api/gocast/api_v2.pbjson.dart
  lib/base/networking/api/google/protobuf/empty.pb.dart
  lib/base/networking/api/google/protobuf/empty.pbenum.dart
  lib/base/networking/api/google/protobuf/empty.pbjson.dart
  lib/base/networking/api/google/protobuf/timestamp.pb.dart
  lib/base/networking/api/google/protobuf/timestamp.pbenum.dart
  lib/base/networking/api/google/protobuf/timestamp.pbjson.dart
  lib/base/networking/api/handler/auth_handler.dart
  lib/base/networking/api/handler/bookmarks_handler.dart
  lib/base/networking/api/handler/grpc_handler.dart
  lib/main.dart
  lib/models/user/user_state_model.dart
  lib/view_models/user_view_model.dart
  lib/views/components/viewall_button_view.dart
  lib/views/course_view/downloaded_pinned_courses_view/downloaded_courses_view.dart
  lib/views/on_boarding_view/welcome_screen_view.dart
  lib/views/settings_view/settings_screen_view.dart
  lib/views/video_view/video_card_view.dart
  lib/views/video_view/video_fullscreen_view.dart
  lib/views/video_view/video_player_view.dart
  proto/gocast/api_v2.proto
Labels: bug, good first issue, flutter

#117 116 fix teamid and bundel when running xcode
  ios/Runner.xcodeproj/project.pbxproj
Labels: bug

#118 fix `padding` for buttons, `internal link` UI
  lib/views/on_boarding_view/welcome_screen_view.dart
Labels: enhancement

#123 122-fix-padding-on-downloads-view
  lib/main.dart
  lib/views/components/base_view.dart
  lib/views/video_view/video_card_view.dart
Labels: flutter, ui

#128 103 add-streaminghandler-and-settingshandler
  lib/base/networking/api/handler/stream_handler.dart
  lib/views/on_boarding_view/welcome_screen_view.dart
Labels: api, flutter

#132 109 move-token-removal-to-the-tokenhandler
  lib/base/networking/api/handler/token_handler.dart
  lib/view_models/user_view_model.dart
Labels: enhancement

#133 131 resolve-reloading-issue-on-pinned-courses-view
  lib/views/course_view/components/pinned_course_list.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
Labels: enhancement, flutter, ui

#147 124 create-a-search-and-filter-button
  lib/views/components/custom_search_filter_top_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/course_view/components/pinned_course_list.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_base_view.dart
Labels: enhancement, flutter, ui

#144 75 implement a video view UI
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/main.dart
  lib/models/user/mock_data.dart
  lib/models/user/user_state_model.dart
  lib/models/video/stream_state_model.dart
  lib/providers.dart
  lib/view_models/stream_view_model.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/components/view_all_button.dart
  lib/views/components/viewall_button_view.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_base_view.dart
  lib/views/on_boarding_view/welcome_screen_view.dart
  lib/views/video_view/chat_video_view.dart
  lib/views/video_view/video_fullscreen_view.dart
  lib/views/video_view/video_player.dart
  lib/views/video_view/video_player_controller.dart
  lib/views/video_view/video_player_view.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, flutter

#135 Style notifications screen
  lib/base/helpers/model_generator.dart
  lib/base/networking/api/gocast/api_v2.pb.dart
  lib/base/networking/api/gocast/api_v2.pbgrpc.dart
  lib/base/networking/api/gocast/api_v2.pbjson.dart
  lib/base/networking/api/handler/notification_handler.dart
  lib/models/user/mock_data.dart
  lib/models/user/user_state_model.dart
  lib/view_models/user_view_model.dart
  lib/views/components/custom_bottom_nav_bar.dart
  lib/views/components/custom_search_filter_top_nav_bar.dart
  lib/views/course_view/components/pinned_course_card.dart
  lib/views/course_view/list_courses_view/my_courses_view.dart
  lib/views/course_view/list_courses_view/public_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/notifications_view/notifications_overview.dart
  lib/views/notifications_view/notifications_screen_view.dart
  lib/views/on_boarding_view/welcome_screen_view.dart
  proto/gocast/api_v2.proto
Labels: flutter, ui

#154 106 - Removing the back-arrow in course_overview_screen
  lib/views/components/base_view.dart
  lib/views/course_view/courses_overview.dart
Labels: bug

#156 105 fix navigation system problems
  lib/main.dart
  lib/navigation_tab.dart
  lib/providers.dart
  lib/view_models/user_view_model.dart
  lib/views/components/base_view.dart
  lib/views/components/custom_bottom_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/course_view/components/courselist_screen.dart
  lib/views/course_view/courses_overview.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/notifications_view/notifications_screen_view.dart
Labels: bug

#158 157 bug-header-is-missing-on-pinned-courses
  lib/views/components/custom_search_top_nav_bar.dart
Labels: bug, flutter, ui

#165 160-fix-info-text-on-pinned-courses
  lib/views/course_view/components/pinned_course_card.dart
  lib/views/course_view/components/pinned_course_list.dart
Labels: flutter, ui

#164 136 implement course view
  lib/models/video/stream_state_model.dart
  lib/view_models/stream_view_model.dart
  lib/view_models/user_view_model.dart
  lib/views/components/custom_search_top_nav_bar_back_button.dart
  lib/views/course_detail_view/course_detail_view.dart
  lib/views/course_detail_view/stream_card.dart
  lib/views/course_view/components/course_card_view.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/components/courses_screen.dart
Labels: flutter, ui

#169 168-[Bug]-Fix-expanded-exception
  lib/navigation_tab.dart
Labels: bug, flutter

#161 #102-Improve-My-courses-and-public-courses-view-UI
  lib/views/course_view/components/course_card_view.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/courses_overview.dart
Labels: flutter, ui
