Repository TUM-Dev/gocast_mobile, pull requests merged in 2024-01, with the labels that each got.

#155 126-fetch-lecture-streams
  lib/base/helpers/mock_data.dart
  lib/base/helpers/model_generator.dart
  lib/base/networking/api/gocast/api_v2.pbgrpc.dart
  lib/base/networking/api/handler/stream_handler.dart
  lib/models/video/stream_state_model.dart
  lib/providers.dart
  lib/view_models/stream_view_model.dart
  lib/views/components/base_view.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/course_detail_view/course_detail_view.dart
  lib/views/course_view/components/course_card_view.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/components/courselist_screen.dart
  lib/views/course_view/components/pinned_course_card.dart
  lib/views/course_view/components/pinned_course_list.dart
  lib/views/course_view/downloaded_courses_view/content_view.dart
  lib/views/course_view/downloaded_courses_view/download_card.dart
  lib/views/course_view/downloaded_courses_view/download_content_view.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/course_view/list_courses_view/courses_list_view.dart
  lib/views/course_view/list_courses_view/my_courses_view.dart
  lib/views/course_view/list_courses_view/public_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_card.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_base_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_content_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/notifications_view/notifications_screen_view.dart
  lib/views/video_view/chat_video_view.dart
  lib/views/video_view/custom_video_control_bar.dart
  lib/views/video_view/video_player.dart
  lib/views/video_view/video_player_controller.dart
Labels: flutter

#176 48-fetch-users-settings
  lib/base/networking/api/handler/settings_handler.dart
  lib/view_models/user_view_model.dart
Labels: flutter

#185 184 pin course in detail course view
  lib/views/course_view/components/pin_button.dart
  lib/views/course_view/course_detail_view/course_detail_view.dart
  lib/views/course_view/pinned_courses_view/pinned_card.dart
Labels: flutter

#174 163-revise-ipad-settings-UI
  lib/views/components/base_view.dart
  lib/views/course_view/components/course_card.dart
  lib/views/course_view/courses_overview.dart
  lib/views/settings_view/settings_screen_view.dart
Labels: ui

#200 177 add control bar to video player in fullscreen and basic ChatUI for android and iOS
  lib/base/networking/api/handler/settings_handler.dart
  lib/view_models/user_view_model.dart
  lib/views/chat_view/chat_video_view.dart
  lib/views/video_view/chat_video_view.dart
  lib/views/video_view/custom_video_control_bar.dart
  lib/views/video_view/utils/custom_video_control_bar.dart
  lib/views/video_view/utils/video_player_handler.dart
  lib/views/video_view/video_player.dart
  lib/views/video_view/video_player_controller.dart
  pubspec.lock
  pubspec.yaml
  setup_grpc.sh
Labels: flutter

#208 207-adjust-the-playback-speed-to-make-one-is-always-be-enabled
  lib/views/settings_view/playback_speed_picker_view.dart
Labels: enhancement, flutter, ui

#172 73 implement push notifications
  README.md
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Runner/GoogleService-Info.plist
  ios/firebase_app_id_file.json
  lib/base/networking/api/gocast/api_v2.pbgrpc.dart
  lib/base/networking/api/handler/auth_handler.dart
  lib/base/networking/api/handler/grpc_handler.dart
  lib/base/networking/api/handler/notification_handler.dart
  lib/base/networking/api/handler/pinned_handler.dart
  lib/base/networking/api/handler/settings_handler.dart
  lib/base/networking/api/handler/token_handler.dart
  lib/config/app_config.dart
  lib/firebase_options.dart
  lib/main.dart
  lib/models/error/error_model.dart
  lib/models/notifications/notification_state_model.dart
  lib/models/notifications/push_notification.dart
  lib/models/user/user_state_model.dart
  lib/models/video/stream_state_model.dart
  lib/navigation_tab.dart
  lib/providers.dart
  lib/view_models/download_view_model.dart
  lib/view_models/notification_view_model.dart
  lib/view_models/stream_view_model.dart
  lib/view_models/user_view_model.dart
  lib/views/chat_view/chat_video_view.dart
  lib/views/components/custom_bottom_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar_back_button.dart
  lib/views/components/view_all_button.dart
  lib/views/course_view/components/base_card.dart
  lib/views/course_view/components/course_card.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/course_detail_view/course_detail_view.dart
  lib/views/course_view/course_detail_view/stream_card.dart
  lib/views/course_view/downloaded_courses_view/download_card.dart
  lib/views/course_view/downloaded_courses_view/download_content_view.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_card.dart
  lib/views/notifications_view/notifications_overview.dart
  lib/views/notifications_view/notifications_screen_view.dart
  lib/views/settings_view/settings_screen_view.dart
  lib/views/video_view/offline_video_player/offline_video_player.dart
  lib/views/video_view/offline_video_player/offline_video_player_controller.dart
  lib/views/video_view/utils/custom_video_control_bar.dart
  lib/views/video_view/utils/video_player_handler.dart
  lib/views/video_view/video_player.dart
  lib/views/video_view/video_player_controller.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, flutter, blocked

#209 85 implement chat functionalities using the api
  ios/Podfile.lock
  ios/Runner/Runner.entitlements
  lib/base/networking/api/gocast/api_v2.pb.dart
  lib/base/networking/api/gocast/api_v2.pbenum.dart
  lib/base/networking/api/gocast/api_v2.pbgrpc.dart
  lib/base/networking/api/gocast/api_v2.pbjson.dart
  lib/base/networking/api/google/protobuf/empty.pb.dart
  lib/base/networking/api/google/protobuf/empty.pbenum.dart
  lib/base/networking/api/google/protobuf/empty.pbjson.dart
  lib/base/networking/api/google/protobuf/timestamp.pb.dart
  lib/base/networking/api/google/protobuf/timestamp.pbenum.dart
  lib/base/networking/api/google/protobuf/timestamp.pbjson.dart
  lib/base/networking/api/handler/chat_handler.dart
  lib/base/networking/api/handler/course_handler.dart
  lib/main.dart
  lib/models/chat/chat_state_model.dart
  lib/models/course/course_state_model.dart
  lib/providers.dart
  lib/view_models/chat_view_model.dart
  lib/view_models/course_view_model.dart
  lib/view_models/user_view_model.dart
  lib/views/chat_view/chat_video_view.dart
  lib/views/chat_view/chat_view.dart
  lib/views/chat_view/chat_view_state.dart
  lib/views/chat_view/suggested_streams_list.dart
  lib/views/video_view/offline_video_player/offline_video_player.dart
  lib/views/video_view/utils/custom_video_control_bar.dart
  lib/views/video_view/video_player.dart
  lib/views/video_view/video_player_controller.dart
  proto/gocast/api_v2.proto
  pubspec.lock
  pubspec.yaml
Labels: flutter

#210 197 search and filter function
  lib/base/networking/api/handler/course_handler.dart
  lib/models/user/user_state_model.dart
  lib/models/video/stream_state_model.dart
  lib/utils/sort_utils.dart
  lib/utils/theme.dart
  lib/view_models/stream_view_model.dart
  lib/view_models/user_view_model.dart
  lib/views/components/base_view.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar_back_button.dart
  lib/views/components/filter_popup_menu_button.dart
  lib/views/course_view/course_detail_view/course_detail_view.dart
  lib/views/course_view/courses_overview.dart
  lib/views/course_view/downloaded_courses_view/download_content_view.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/course_view/list_courses_view/courses_list_view.dart
  lib/views/course_view/list_courses_view/my_courses_view.dart
  lib/views/course_view/list_courses_view/public_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_content_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/settings_view/settings_screen_view.dart
  pubspec.lock
  pubspec.yaml
Labels: flutter

#237 #134-Create-new-home-design
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/models/download/download_state_model.dart
  lib/providers.dart
  lib/view_models/download_view_model.dart
  lib/view_models/stream_view_model.dart
  lib/views/components/base_view.dart
  lib/views/components/view_all_button.dart
  lib/views/course_view/components/base_card.dart
  lib/views/course_view/components/course_card.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/components/pulse_background.dart
  lib/views/course_view/components/stream_card.dart
  lib/views/course_view/course_detail_view/course_detail_view.dart
  lib/views/course_view/course_detail_view/stream_card.dart
  lib/views/course_view/courses_overview.dart
  lib/views/course_view/downloaded_courses_view/download_content_view.dart
  lib/views/course_view/list_courses_view/courses_list_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_content_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/settings_view/settings_screen_view.dart
  pubspec.lock
  pubspec.yaml
Labels: flutter, ui

#248 Fix the displayed courses state and add swipe gesture to pin-unpin a course
  lib/base/networking/api/gocast/api_v2.pb.dart
  lib/base/networking/api/gocast/api_v2.pbenum.dart
  lib/base/networking/api/gocast/api_v2.pbgrpc.dart
  lib/base/networking/api/gocast/api_v2.pbjson.dart
  lib/base/networking/api/google/protobuf/empty.pb.dart
  lib/base/networking/api/google/protobuf/empty.pbenum.dart
  lib/base/networking/api/google/protobuf/empty.pbjson.dart
  lib/base/networking/api/google/protobuf/timestamp.pb.dart
  lib/base/networking/api/google/protobuf/timestamp.pbenum.dart
  lib/base/networking/api/google/protobuf/timestamp.pbjson.dart
  lib/base/networking/api/handler/chat_handler.dart
  lib/base/networking/api/handler/course_handler.dart
  lib/base/networking/api/handler/settings_handler.dart
  lib/base/networking/api/handler/stream_handler.dart
  lib/models/chat/chat_state_model.dart
  lib/models/course/course_state_model.dart
  lib/models/settings/setting_state_model.dart
  lib/models/user/user_state_model.dart
  lib/models/video/stream_state_model.dart
  lib/providers.dart
  lib/utils/sort_utils.dart
  lib/view_models/chat_view_model.dart
  lib/view_models/course_view_model.dart
  lib/view_models/download_view_model.dart
  lib/view_models/setting_view_model.dart
  lib/view_models/stream_view_model.dart
  lib/view_models/user_view_model.dart
  lib/views/chat_view/chat_view.dart
  lib/views/chat_view/chat_view_state.dart
  lib/views/chat_view/suggested_streams_list.dart
  lib/views/components/base_view.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar_back_button.dart
  lib/views/course_view/components/base_card.dart
  lib/views/course_view/components/course_card.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/components/stream_card.dart
  lib/views/course_view/courses_overview.dart
  lib/views/course_view/list_courses_view/courses_list_view.dart
  lib/views/course_view/list_courses_view/my_courses_view.dart
  lib/views/course_view/list_courses_view/public_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_content_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/notifications_view/notifications_screen_view.dart
  lib/views/settings_view/settings_screen_view.dart
  lib/views/video_view/video_player.dart
  lib/views/video_view/video_player_controller.dart
  proto/gocast/api_v2.proto
  pubspec.lock
  pubspec.yaml
Labels: bug

#242 Adding download over wifi func
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  lib/models/settings/setting_state_model.dart
  lib/view_models/download_view_model.dart
  lib/views/video_view/video_player.dart
  pubspec.lock
  pubspec.yaml
Labels: flutter

#255 Fix Bugs and clean logs
  lib/base/networking/api/handler/api_handler.dart
  lib/base/networking/api/handler/auth_handler.dart
  lib/base/networking/api/handler/bookmarks_handler.dart
  lib/base/networking/api/handler/chat_handler.dart
  lib/base/networking/api/handler/course_handler.dart
  lib/base/networking/api/handler/grpc_handler.dart
  lib/base/networking/api/handler/notification_handler.dart
  lib/base/networking/api/handler/pinned_handler.dart
  lib/base/networking/api/handler/poll_handler.dart
  lib/base/networking/api/handler/settings_handler.dart
  lib/base/networking/api/handler/stream_handler.dart
  lib/base/networking/api/handler/token_handler.dart
  lib/base/networking/api/handler/user_handler.dart
  lib/models/course/pinned_course_state_model.dart
  lib/models/error/error_model.dart
  lib/models/user/user_state_model.dart
  lib/providers.dart
  lib/view_models/chat_view_model.dart
  lib/view_models/course_view_model.dart
  lib/view_models/notification_view_model.dart
  lib/view_models/pinned_view_model.dart
  lib/view_models/poll_view_model.dart
  lib/view_models/setting_view_model.dart
  lib/view_models/stream_view_model.dart
  lib/view_models/user_view_model.dart
  lib/views/chat_view/chat_view_state.dart
  lib/views/components/filter_popup_menu_button.dart
  lib/views/course_view/components/course_section.dart
  lib/views/course_view/components/pin_button.dart
  lib/views/course_view/course_detail_view/course_detail_view.dart
  lib/views/course_view/courses_overview.dart
  lib/views/course_view/list_courses_view/courses_list_view.dart
  lib/views/course_view/list_courses_view/public_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/login_view/internal_login_view.dart
  lib/views/video_view/utils/custom_video_control_bar.dart
Labels: bug

#246 225 Add course name on downloads card UI
  lib/models/download/download_state_model.dart
  lib/view_models/download_view_model.dart
  lib/views/course_view/components/course_card.dart
  lib/views/course_view/components/small_stream_card.dart
  lib/views/course_view/downloaded_courses_view/download_content_view.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/video_view/video_player.dart
Labels: flutter

#262 Bug chat state not updating and add internationalization
  l10n.yaml
  lib/base/helpers/mock_data.dart
  lib/base/networking/api/handler/grpc_handler.dart
  lib/config/app_config.dart
  lib/l10n/app_de.arb
  lib/l10n/app_en.arb
  lib/l10n/app_es.arb
  lib/l10n/app_fr.arb
  lib/l10n/l10n.dart
  lib/main.dart
  lib/utils/UserPreferences.dart
  lib/view_models/chat_view_model.dart
  lib/view_models/setting_view_model.dart
  lib/views/chat_view/chat_view_state.dart
  lib/views/chat_view/inactive_view.dart
  lib/views/chat_view/poll_view_state.dart
  lib/views/components/custom_bottom_nav_bar.dart
  lib/views/components/custom_search_filter_top_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar.dart
  lib/views/components/custom_search_top_nav_bar_back_button.dart
  lib/views/course_view/components/base_card.dart
  lib/views/course_view/components/course_card.dart
  lib/views/course_view/components/pulse_background.dart
  lib/views/course_view/components/small_stream_card.dart
  lib/views/course_view/course_detail_view/course_detail_view.dart
  lib/views/course_view/courses_overview.dart
  lib/views/course_view/downloaded_courses_view/download_card.dart
  lib/views/course_view/downloaded_courses_view/download_content_view.dart
  lib/views/course_view/downloaded_courses_view/downloaded_courses_view.dart
  lib/views/course_view/list_courses_view/courses_list_view.dart
  lib/views/course_view/list_courses_view/my_courses_view.dart
  lib/views/course_view/list_courses_view/public_courses_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_content_view.dart
  lib/views/course_view/pinned_courses_view/pinned_courses_view.dart
  lib/views/login_view/internal_login_view.dart
  lib/views/notifications_view/notifications_overview.dart
  lib/views/notifications_view/notifications_screen_view.dart
  lib/views/on_boarding_view/enable_notification_view.dart
  lib/views/on_boarding_view/welcome_screen_view.dart
  lib/views/settings_view/authentication_error_card_view.dart
  lib/views/settings_view/custom_playback_speed_view.dart
  lib/views/settings_view/edit_profile_screen_view.dart
  lib/views/settings_view/playback_speed_picker_view.dart
  lib/views/settings_view/playback_speed_settings_view.dart
  lib/views/settings_view/preferred_greeting_view.dart
  lib/views/settings_view/settings_screen_view.dart
  lib/views/video_view/video_player.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement
